# Generated by Django 5.1.2 on 2024-10-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("phoneNumber", models.CharField(max_length=12)),
                ("gender", models.CharField(max_length=25)),
                ("Dob", models.DateField()),
                ("membershipPlan", models.CharField(max_length=300)),
                ("trainer", models.CharField(max_length=55)),
                ("reference", models.CharField(max_length=55)),
                ("address", models.TextField()),
                ("timestamp", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MembershipPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan", models.CharField(max_length=55)),
                ("price", models.IntegerField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=55)),
                ("gender", models.CharField(max_length=20)),
                ("phone", models.CharField(max_length=12)),
                ("salary", models.IntegerField(max_length=25)),
            ],
        ),
    ]
