# Generated by Django 5.1.2 on 2024-10-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0002_enroll_membershipplan_trainer"),
    ]

    operations = [
        migrations.AddField(
            model_name="enroll",
            name="dueDate",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enroll",
            name="paymentStatus",
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name="enroll",
            name="price",
            field=models.IntegerField(blank=True, max_length=55, null=True),
        ),
    ]
