# Generated by Django 5.1.2 on 2024-10-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0004_rename_trainer_enroll_trainers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("img", models.ImageField(upload_to="gallery")),
                ("timestamp", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
