# Generated by Django 5.1.2 on 2024-10-28 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0006_attendance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="Login",
            new_name="login",
        ),
    ]
